### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 18PatZ**
Yo dawg, you guys did not contribute to these solution hehe xd

### CODE REVIEW

**Comment by 18AdrianoH** [comment]
We were working on it dude.  We also solved problem 1.

**Comment by 18AdrianoH** [comment]
This is why I put your name first haha.

**Comment by 18PatZ** [comment]
Triggered that code isn't yours though

**Comment by 18PatZ** [comment]
You can put your problem 1 code in a team28 folder

**Pull request closed without merging**
